image: "ringcentral/maven"

stages:
  - build
  - deploy

build:
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/
  stage: build


deploy:
  image: docker
  script:
    - ls -l
    - service docker start
    - docker image build -t gyst .
    - docker image ls
  stage: deploy
