image: "openjdk:8"

before_script:
  - echo "hello this is before script execution"

build:
  script:
    - echo "hi this is build"

test:
  script:
    - echo "hi this is test"

deploy:
  script:
    - echo "hi this is hello"
