image: "ringcentral/maven"

stages:
  - test
  - build
  - deploy

before_script:
  - echo "hello this is before script execution"

test:
  script:
    - mvn clean test
  stage: test

build:
  script:
    - echo "hi this is build"
  stage: build


deploy:
  script:
    - echo "hi this is hello"
  stage: deploy
