image: "ringcentral/maven"

stages:
  - build
  - deploy

build:
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/
  stage: build


deploy:
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  script:
    - ls -l
    - docker image build -t gyst .
    - docker image ls
  stage: deploy
